version: '2'
services:
  remote_user_proxy:
    image: quay.io/erasche/remote_user_proxy:latest
    links:
      - apollo:target
    ports:
      - 8080:80
    environment:
      BACKEND_URL: "http://target:8080"
      REMOTE_USER: admin@local.host
  apollo:
    image: quay.io/erasche/apollo:remote_user
    links:
      - db
      - chado
    environment:
      CONTEXT_PATH: ROOT
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
      WEBAPOLLO_CHADO_DB_USERNAME: postgres
      WEBAPOLLO_CHADO_DB_PASSWORD: password
      WEBAPOLLO_CHADO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_CHADO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_CHADO_DB_URI: "jdbc:postgresql://chado/postgres"
      # Optional, allow image to 'wait'
      WEBAPOLLO_DB_HOST: db
      WEBAPOLLO_DB_PORT: 5432
      WEBAPOLLO_DB_NAME: postgres
      WEBAPOLLO_CHADO_DB_HOST: chado
      WEBAPOLLO_CHADO_DB_PORT: 5432
      WEBAPOLLO_CHADO_DB_NAME: postgres
    volumes:
      - "./data:/data"
  db:
    image: erasche/chado:1.31-jenkins97-pg9.5
    environment:
      POSTGRES_PASSWORD: password
      INSTALL_CHADO_SCHEMA: "0"
  chado:
    image: erasche/chado:1.31-jenkins97-pg9.5
    environment:
      - POSTGRES_PASSWORD=password
      # The default chado image would try to install the schema on first run
      #- INSTALL_CHADO_SCHEMA=0
    volumes:
      - /var/lib/postgresql/9.4/
